@startuml
actor Estudiante
actor Docente
actor Comision

rectangle "Sistema SED" {
    (Iniciar sesión) as UC1
    (Estabilizar controles de acceso por rol) as UC2
    (Acceder a panel de estudiante) as UC3
    (Acceder a panel de docente) as UC4
    (Acceder a panel administrativo) as UC5

    UC1 --> UC2 : <<include>>
    UC2 --> UC3 : <<extend>>
    UC2 --> UC4 : <<extend>>
    UC2 --> UC5 : <<extend>>
}

Estudiante --> UC1
Docente --> UC1
Comision --> UC1
@enduml
