# Generated by Django 5.2.1 on 2025-05-16 23:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioEvaluacion',
            fields=[
                ('idCriterio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoEvaluacion',
            fields=[
                ('idPeriodo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('idEvaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('comentarios', models.TextField()),
                ('estado_final', models.CharField(max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.docente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEvaluacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valoracion', models.IntegerField()),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.criterioevaluacion')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionPendiente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.docente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEvaluacion',
            fields=[
                ('idHistorial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateField()),
                ('descripcion_cambio', models.TextField()),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.evaluacion')),
            ],
        ),
    ]
